import {useState} from "react";
import type { NextPage } from 'next'
import Head from 'next/head';

import PixelCanvas from "../components/pixel-canvas/pixel-canvas";
import PaletteBar from "../components/palette-bar/palette-bar";
import PixelCoordinates from "../components/pixel-coordinates/pixel-coordinates";
import PixelPlaceBtn from "../components/pixel-place-btn/pixel-place-btn";
import {FakeSyncer} from "../components/live-canvas/fake-syncer";
import {useLiveCanvasSync} from "../components/live-canvas/use-live-canvas-sync";
import InkWalletPanel from "../components/ink-wallet-panel/ink-wallet-panel";

const createSyncer = () => new FakeSyncer;

const Home: NextPage = () => {
  useLiveCanvasSync(createSyncer);
  const [isEditing, setIsEditing] = useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta content="initial-scale=1.0, user-scalable=no" name="viewport" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ backgroundColor: '#121213' }}>
        <InkWalletPanel />
        <PixelCanvas onClick={() => setIsEditing(!isEditing)} />
        {isEditing && <PaletteBar />}
        {isEditing && <PixelCoordinates />}
        {isEditing && <PixelPlaceBtn />}
      </main>
    </>
  )
};

export default Home;
