import {useState} from "react";
import type { NextPage } from 'next'
import Head from 'next/head';

import InkWalletPanel from "../components/ink-wallet-panel/ink-wallet-panel";
import PixelCanvas from "../components/pixel-canvas/pixel-canvas";
import {FooterActions} from "../components/footer-actions/footer-actions";


const Home: NextPage = () => {
  const [isEditing, setIsEditing] = useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta content="initial-scale=1.0, user-scalable=no" name="viewport" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ backgroundColor: '#121213' }}>
        <InkWalletPanel />
        <PixelCanvas onClick={() => setIsEditing(!isEditing)} />
      </main>

      <footer>
        {isEditing && <FooterActions />}
      </footer>
    </>
  )
};

export default Home;
